/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.searcher;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import java.io.File;
import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
/**
 *
 * @author junyoung
 */
public class UserInterface extends javax.swing.JFrame implements PropertyChangeListener {

    private PDFManager pdfManager = new PDFManager();;
    private boolean searchBoxButtonFlag = true;
    private boolean NavigationBoxButtonFlag = true;
    private boolean ResultBoxButtonFlag = true;
    private boolean lock = false;
    private boolean isFileSelected = false;

    /**
     * Creates new form SearchPanelInterface
     */
    public UserInterface() throws Exception {
        initComponents();
        pdfManager.resultHandler.addPropertyChangeListener(this);
    }

    // if lock change detected
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if ("lock".equals(evt.getPropertyName())) {
            lock = (Boolean) evt.getNewValue();
            if (lock) {
                lock();
            } else {
                unlock();
            }
        }
    }

    private void openDocument(String filepath) {
        pdfManager.openDocument(filepath);
    }

    private void lock() {
        lock = true;
        SearchButton.setEnabled(false);
        NavigationOpenButton.setEnabled(false);
        SearchStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/duck_resized.gif")));
    }
    private void unlock() {
        lock = false;
        if (isFileSelected) {
            SearchButton.setEnabled(true);
        }
        NavigationOpenButton.setEnabled(true);
        SearchStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/check_resized.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MainPanel = new javax.swing.JPanel();
        PDFViewPanel = new javax.swing.JPanel();
        SearchBoxActivationButton = new javax.swing.JButton();
        ResultBoxActivationButton = new javax.swing.JButton();
        NavigationBoxActivationButton = new javax.swing.JButton();
        SearchBoxLayer = new javax.swing.JLayeredPane();
        LexicalSelectorButton = new javax.swing.JButton();
        SemanticSelectorButton = new javax.swing.JButton();
        KeywordSelectorButton = new javax.swing.JButton();
        TextSearchOptions = new javax.swing.JLabel();
        TabPanel = new javax.swing.JTabbedPane();
        Lexical = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        SearchInput = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        SearchOptions = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Keyword = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        KeywordSearchInput = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<>();
        KeywordSearchOptions = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        Semantic = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        KeywordSearchInput1 = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        SearchInfoPanel = new javax.swing.JPanel();
        SearchStatus = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        SearchMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultBoxLayer = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        NavigationBoxLayer = new javax.swing.JLayeredPane();
        NavigationMainPanel = new javax.swing.JPanel();
        NavigationLabel = new javax.swing.JLabel();
        NavigationOpenButton = new javax.swing.JButton();
        OpenedDocumentListScrollPane = new javax.swing.JScrollPane();
        OpenedDocumentList = new javax.swing.JList<>();
        NavigationSelectButton = new javax.swing.JButton();
        NavigationViewButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setPreferredSize(new java.awt.Dimension(1600, 900));

        PDFViewPanel.setBackground(new java.awt.Color(204, 204, 255));
        PDFViewPanel.setMaximumSize(new java.awt.Dimension(1600, 900));
        PDFViewPanel.setMinimumSize(new java.awt.Dimension(1040, 603));
        PDFViewPanel.setLayout(new java.awt.GridBagLayout());

        SearchBoxActivationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/up_arrow_resized.png"))); // NOI18N
        SearchBoxActivationButton.setBorderPainted(false);
        SearchBoxActivationButton.setContentAreaFilled(false);
        SearchBoxActivationButton.setFocusPainted(false);
        SearchBoxActivationButton.setMaximumSize(new java.awt.Dimension(100, 100));
        SearchBoxActivationButton.setMinimumSize(new java.awt.Dimension(70, 40));
        SearchBoxActivationButton.setPreferredSize(new java.awt.Dimension(70, 40));
        SearchBoxActivationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBoxActivationButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        PDFViewPanel.add(SearchBoxActivationButton, gridBagConstraints);

        ResultBoxActivationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/right_arrow_resized.png"))); // NOI18N
        ResultBoxActivationButton.setContentAreaFilled(false);
        ResultBoxActivationButton.setMinimumSize(new java.awt.Dimension(40, 70));
        ResultBoxActivationButton.setPreferredSize(new java.awt.Dimension(40, 70));
        ResultBoxActivationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultBoxActivationButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(305, 6, 0, 17);
        PDFViewPanel.add(ResultBoxActivationButton, gridBagConstraints);

        NavigationBoxActivationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left_arrow_resized.png"))); // NOI18N
        NavigationBoxActivationButton.setContentAreaFilled(false);
        NavigationBoxActivationButton.setMaximumSize(new java.awt.Dimension(40, 70));
        NavigationBoxActivationButton.setMinimumSize(new java.awt.Dimension(40, 70));
        NavigationBoxActivationButton.setPreferredSize(new java.awt.Dimension(40, 70));
        NavigationBoxActivationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavigationBoxActivationButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(305, 6, 0, 0);
        PDFViewPanel.add(NavigationBoxActivationButton, gridBagConstraints);

        SearchBoxLayer.setBackground(new java.awt.Color(204, 204, 204));
        SearchBoxLayer.setToolTipText("");
        SearchBoxLayer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SearchBoxLayer.setDoubleBuffered(true);
        SearchBoxLayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LexicalSelectorButton.setText("Lexical Search");
        LexicalSelectorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LexicalSelectorButtonActionPerformed(evt);
            }
        });
        SearchBoxLayer.add(LexicalSelectorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 200, 50));

        SemanticSelectorButton.setText("Semantic Search");
        SemanticSelectorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemanticSelectorButtonActionPerformed(evt);
            }
        });
        SearchBoxLayer.add(SemanticSelectorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 200, 50));

        KeywordSelectorButton.setText("Keyword Search");
        KeywordSelectorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeywordSelectorButtonActionPerformed(evt);
            }
        });
        SearchBoxLayer.add(KeywordSelectorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, 50));

        TextSearchOptions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextSearchOptions.setText("Search Options");
        TextSearchOptions.setFocusable(false);
        TextSearchOptions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SearchBoxLayer.add(TextSearchOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 39));

        Title.setText("Lexical Search");
        Title.setMaximumSize(new java.awt.Dimension(170, 20));
        Title.setMinimumSize(new java.awt.Dimension(170, 20));

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField1");

        jTextField3.setText("jTextField1");

        jTextField4.setText("jTextField1");

        jTextField5.setText("jTextField1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout SearchInputLayout = new javax.swing.GroupLayout(SearchInput);
        SearchInput.setLayout(SearchInputLayout);
        SearchInputLayout.setHorizontalGroup(
            SearchInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchInputLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(SearchInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SearchInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jTextField3))
                .addGap(30, 30, 30))
        );
        SearchInputLayout.setVerticalGroup(
            SearchInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchInputLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SearchInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SearchInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SearchInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SearchInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Seach Range:");

        javax.swing.GroupLayout SearchOptionsLayout = new javax.swing.GroupLayout(SearchOptions);
        SearchOptions.setLayout(SearchOptionsLayout);
        SearchOptionsLayout.setHorizontalGroup(
            SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SearchOptionsLayout.setVerticalGroup(
            SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchOptionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout LexicalLayout = new javax.swing.GroupLayout(Lexical);
        Lexical.setLayout(LexicalLayout);
        LexicalLayout.setHorizontalGroup(
            LexicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LexicalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(LexicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LexicalLayout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(LexicalLayout.createSequentialGroup()
                        .addComponent(SearchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LexicalLayout.setVerticalGroup(
            LexicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LexicalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LexicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SearchOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabPanel.addTab("tab1", Lexical);

        jLabel6.setText("Keyword Search");

        jTextField7.setText("jTextField1");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel4.setText("Keyword Input: (word only)");

        jLabel7.setText("Part-of-Speech Tag:");

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout KeywordSearchInputLayout = new javax.swing.GroupLayout(KeywordSearchInput);
        KeywordSearchInput.setLayout(KeywordSearchInputLayout);
        KeywordSearchInputLayout.setHorizontalGroup(
            KeywordSearchInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeywordSearchInputLayout.createSequentialGroup()
                .addGap(0, 112, Short.MAX_VALUE)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(KeywordSearchInputLayout.createSequentialGroup()
                .addGroup(KeywordSearchInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KeywordSearchInputLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(KeywordSearchInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(KeywordSearchInputLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        KeywordSearchInputLayout.setVerticalGroup(
            KeywordSearchInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeywordSearchInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCheckBox1.setText("Include Synonyms");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KeywordSearchOptionsLayout = new javax.swing.GroupLayout(KeywordSearchOptions);
        KeywordSearchOptions.setLayout(KeywordSearchOptionsLayout);
        KeywordSearchOptionsLayout.setHorizontalGroup(
            KeywordSearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCheckBox1)
        );
        KeywordSearchOptionsLayout.setVerticalGroup(
            KeywordSearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeywordSearchOptionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addContainerGap())
        );

        javax.swing.GroupLayout KeywordLayout = new javax.swing.GroupLayout(Keyword);
        Keyword.setLayout(KeywordLayout);
        KeywordLayout.setHorizontalGroup(
            KeywordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeywordLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(KeywordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KeywordLayout.createSequentialGroup()
                        .addComponent(KeywordSearchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(KeywordSearchOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        KeywordLayout.setVerticalGroup(
            KeywordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeywordLayout.createSequentialGroup()
                .addGroup(KeywordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(KeywordLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(KeywordSearchOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(KeywordLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(KeywordSearchInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );

        TabPanel.addTab("tab2", Keyword);

        jLabel2.setText("Semantic Search");

        jTextField11.setText("jTextField1");

        jLabel8.setText("Sentence similar to:");

        jLabel9.setText("Similarity Threshold:");

        jSlider1.setMajorTickSpacing(10);
        jSlider1.setMaximum(90);
        jSlider1.setMinimum(20);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setToolTipText("");

        javax.swing.GroupLayout KeywordSearchInput1Layout = new javax.swing.GroupLayout(KeywordSearchInput1);
        KeywordSearchInput1.setLayout(KeywordSearchInput1Layout);
        KeywordSearchInput1Layout.setHorizontalGroup(
            KeywordSearchInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeywordSearchInput1Layout.createSequentialGroup()
                .addGap(0, 112, Short.MAX_VALUE)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(KeywordSearchInput1Layout.createSequentialGroup()
                .addGroup(KeywordSearchInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KeywordSearchInput1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(KeywordSearchInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(KeywordSearchInput1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        KeywordSearchInput1Layout.setVerticalGroup(
            KeywordSearchInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeywordSearchInput1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SemanticLayout = new javax.swing.GroupLayout(Semantic);
        Semantic.setLayout(SemanticLayout);
        SemanticLayout.setHorizontalGroup(
            SemanticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SemanticLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(SemanticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KeywordSearchInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        SemanticLayout.setVerticalGroup(
            SemanticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SemanticLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(KeywordSearchInput1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabPanel.addTab("tab3", Semantic);

        SearchBoxLayer.add(TabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, -45, 800, 330));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        PDFViewPanel.add(SearchBoxLayer, gridBagConstraints);

        SearchInfoPanel.setBackground(new java.awt.Color(204, 204, 255));
        SearchInfoPanel.setMinimumSize(new java.awt.Dimension(1107, 30));

        SearchStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/duck_resized.gif"))); // NOI18N
        SearchStatus.setText("Status:");
        SearchStatus.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        SearchButton.setText("Search");
        SearchButton.setEnabled(false);
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        SearchMessage.setText("Search message");

        javax.swing.GroupLayout SearchInfoPanelLayout = new javax.swing.GroupLayout(SearchInfoPanel);
        SearchInfoPanel.setLayout(SearchInfoPanelLayout);
        SearchInfoPanelLayout.setHorizontalGroup(
            SearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 544, Short.MAX_VALUE)
                .addComponent(SearchStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton)
                .addGap(12, 12, 12))
        );
        SearchInfoPanelLayout.setVerticalGroup(
            SearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchInfoPanelLayout.createSequentialGroup()
                .addGroup(SearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SearchInfoPanelLayout.createSequentialGroup()
                        .addGroup(SearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SearchInfoPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(SearchMessage))
                            .addGroup(SearchInfoPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        PDFViewPanel.add(SearchInfoPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 883;
        gridBagConstraints.ipady = 497;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.4;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        PDFViewPanel.add(jScrollPane1, gridBagConstraints);

        ResultBoxLayer.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel5.setText("Search Results");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        ResultBoxLayer.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ResultBoxLayerLayout = new javax.swing.GroupLayout(ResultBoxLayer);
        ResultBoxLayer.setLayout(ResultBoxLayerLayout);
        ResultBoxLayerLayout.setHorizontalGroup(
            ResultBoxLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ResultBoxLayerLayout.setVerticalGroup(
            ResultBoxLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        NavigationMainPanel.setBackground(new java.awt.Color(255, 204, 204));

        NavigationLabel.setText("PDF Document Manger");

        NavigationOpenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open_resized.png"))); // NOI18N
        NavigationOpenButton.setText("Open");
        NavigationOpenButton.setEnabled(false);
        NavigationOpenButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        NavigationOpenButton.setIconTextGap(20);
        NavigationOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavigationOpenButtonActionPerformed(evt);
            }
        });

        OpenedDocumentList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        OpenedDocumentListScrollPane.setViewportView(OpenedDocumentList);

        NavigationSelectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/select_resized.png"))); // NOI18N
        NavigationSelectButton.setText("Select");
        NavigationSelectButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        NavigationSelectButton.setIconTextGap(25);
        NavigationSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavigationSelectButtonActionPerformed(evt);
            }
        });

        NavigationViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view_resized.png"))); // NOI18N
        NavigationViewButton.setText("View");
        NavigationViewButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        NavigationViewButton.setIconTextGap(28);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_resized.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton4.setIconTextGap(25);

        javax.swing.GroupLayout NavigationMainPanelLayout = new javax.swing.GroupLayout(NavigationMainPanel);
        NavigationMainPanel.setLayout(NavigationMainPanelLayout);
        NavigationMainPanelLayout.setHorizontalGroup(
            NavigationMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationMainPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(NavigationMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OpenedDocumentListScrollPane)
                    .addComponent(NavigationOpenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NavigationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(NavigationSelectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NavigationViewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        NavigationMainPanelLayout.setVerticalGroup(
            NavigationMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NavigationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NavigationOpenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OpenedDocumentListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NavigationSelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NavigationViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        NavigationBoxLayer.setLayer(NavigationMainPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout NavigationBoxLayerLayout = new javax.swing.GroupLayout(NavigationBoxLayer);
        NavigationBoxLayer.setLayout(NavigationBoxLayerLayout);
        NavigationBoxLayerLayout.setHorizontalGroup(
            NavigationBoxLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationBoxLayerLayout.createSequentialGroup()
                .addComponent(NavigationMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NavigationBoxLayerLayout.setVerticalGroup(
            NavigationBoxLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationBoxLayerLayout.createSequentialGroup()
                .addComponent(NavigationMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(NavigationBoxLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PDFViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1112, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResultBoxLayer)
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResultBoxLayer)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PDFViewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(NavigationBoxLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainPanel, 1588, 1588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1610, 942);
    }// </editor-fold>//GEN-END:initComponents

    private void SemanticSelectorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemanticSelectorButtonActionPerformed
        TabPanel.setSelectedIndex(2);
    }//GEN-LAST:event_SemanticSelectorButtonActionPerformed

    private void KeywordSelectorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeywordSelectorButtonActionPerformed
        TabPanel.setSelectedIndex(1);
    }//GEN-LAST:event_KeywordSelectorButtonActionPerformed

    private void LexicalSelectorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LexicalSelectorButtonActionPerformed
        TabPanel.setSelectedIndex(0);
    }//GEN-LAST:event_LexicalSelectorButtonActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void SearchBoxActivationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBoxActivationButtonActionPerformed
        SearchBoxLayer.setVisible(!SearchBoxLayer.isVisible());
        SearchButton.setVisible(!SearchButton.isVisible());
        if (searchBoxButtonFlag) {
            SearchBoxActivationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/down_arrow_resized.png")));
        } else {
            SearchBoxActivationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/up_arrow_resized.png")));
        }
        searchBoxButtonFlag = !searchBoxButtonFlag;
    }//GEN-LAST:event_SearchBoxActivationButtonActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void ResultBoxActivationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultBoxActivationButtonActionPerformed
        ResultBoxLayer.setVisible(!ResultBoxLayer.isVisible());
        if (ResultBoxButtonFlag) {
            ResultBoxActivationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left_arrow_resized.png")));
        } else {
            ResultBoxActivationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/right_arrow_resized.png")));
        }
        ResultBoxButtonFlag = !ResultBoxButtonFlag;
    }//GEN-LAST:event_ResultBoxActivationButtonActionPerformed

    private void NavigationBoxActivationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavigationBoxActivationButtonActionPerformed
        NavigationBoxLayer.setVisible(!NavigationBoxLayer.isVisible());
        if (NavigationBoxButtonFlag) {
            NavigationBoxActivationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/right_arrow_resized.png")));
        } else {
            NavigationBoxActivationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left_arrow_resized.png")));
        }
        NavigationBoxButtonFlag = !NavigationBoxButtonFlag;
    }//GEN-LAST:event_NavigationBoxActivationButtonActionPerformed

    private void NavigationOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavigationOpenButtonActionPerformed
        final JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filepath = selectedFile.getAbsolutePath();
            if (PDFHandler.isFileValid(filepath)) {
                lock();
                openDocument(filepath);
            } else {
                JOptionPane.showMessageDialog(null, "Invalid file, please select a valid PDF Document!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            System.out.println("Selected file: " + selectedFile.getAbsolutePath());
        } 
    }//GEN-LAST:event_NavigationOpenButtonActionPerformed

    private void NavigationSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavigationSelectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NavigationSelectButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            ControlUtil.stopResultQueueThread();
            ControlUtil.stopSearchEngineThread();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            javax.swing.UIManager.setLookAndFeel( new FlatCyanLightIJTheme() );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UserInterface().setVisible(true);
                } catch (Exception e) {
                    System.err.println(e.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Keyword;
    private javax.swing.JPanel KeywordSearchInput;
    private javax.swing.JPanel KeywordSearchInput1;
    private javax.swing.JPanel KeywordSearchOptions;
    private javax.swing.JButton KeywordSelectorButton;
    private javax.swing.JPanel Lexical;
    private javax.swing.JButton LexicalSelectorButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton NavigationBoxActivationButton;
    private javax.swing.JLayeredPane NavigationBoxLayer;
    private javax.swing.JLabel NavigationLabel;
    private javax.swing.JPanel NavigationMainPanel;
    private javax.swing.JButton NavigationOpenButton;
    private javax.swing.JButton NavigationSelectButton;
    private javax.swing.JButton NavigationViewButton;
    private javax.swing.JList<String> OpenedDocumentList;
    private javax.swing.JScrollPane OpenedDocumentListScrollPane;
    private javax.swing.JPanel PDFViewPanel;
    private javax.swing.JButton ResultBoxActivationButton;
    private javax.swing.JLayeredPane ResultBoxLayer;
    private javax.swing.JButton SearchBoxActivationButton;
    private javax.swing.JLayeredPane SearchBoxLayer;
    private javax.swing.JButton SearchButton;
    private javax.swing.JPanel SearchInfoPanel;
    private javax.swing.JPanel SearchInput;
    private javax.swing.JLabel SearchMessage;
    private javax.swing.JPanel SearchOptions;
    private javax.swing.JLabel SearchStatus;
    private javax.swing.JPanel Semantic;
    private javax.swing.JButton SemanticSelectorButton;
    private javax.swing.JTabbedPane TabPanel;
    private javax.swing.JLabel TextSearchOptions;
    private javax.swing.JLabel Title;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
